### PR TITLE
Misc: Support install without Cython already installed

### PR DESCRIPTION
**Pull request by DomHudson**
## Summary
The primary functionality change proposed is that `pip install ...` should now work even in a fresh environment without `Cython` installed. 

As of `setuptools==18.0`, Cython extensions can be built with just the `Cython` dependency specified in `setup_requires`. The direct import at the top of `setup.py` was preventing this behaviour as the import fails and terminates the code even though the `Cython` setup dependency was specified.

I apply a minor refactor which encapsulates the code related to fetching and traversing the source code into a class. This class can be instantiated with varying directories if you want to download the source code to an alternate location. I have tried to be really explicit in the code as delayed imports and extension parsing can lead to quite cryptic setup files.

I also adjusted double quotes to single quotes as there was a mixture of the two in the file. 

Feedback is very welcome.

### Related Entities
[#18  Old version on pypi does not build with Python 3.7](https://github.com/snowballstem/pystemmer/issues/18)
[#26 Add install Cython before building package](https://github.com/snowballstem/pystemmer/pull/26)

### CODE REVIEW

**Comment by ojwb** [comment]
> I also adjusted double quotes to single quotes as there was a mixture of the two in the file.

That's fine in itself, but doing that in the same commit as functional changes makes this a whole lot harder to review for no good reason...

**Comment by DomHudson** [comment]
I have removed those changes

Many thanks,
Dom

**Comment by ojwb** [comment]
Not wanting to sound negative, but this was still not easy to review due to the fairly extensive refactoring.  If you want to do more refactoring like this, perhaps you should consider taking over as pystemmer maintainer?  I'm not comfortable with merging changes I haven't fully understood, but Python isn't my primary language so reviewing changes such as this is really quite time consuming.

That said, the fix was definitely appreciated.  Thank you.

**Comment by ojwb** [comment]
@DomHudson Sorry, I must have missed the email notification for your last comment, and only just saw it.

I think it would make most sense to either transfer the repo to you, or create a new "pystemmer" org for it and move it there.

**Comment by mihai-tiriplica-hs** [comment]
Hello! Thank you for the work on this. I don't think a release was created for this fix.

**Comment by ojwb** [comment]
@mihai-tiriplica-hs It seems not - the most recent pypi upload was before the merge above.  But you need to talk to the pypi package maintainer (@felixonmars) about that.

**Comment by felixonmars** [comment]
Perhaps a version bump in the repo is expected besides the PyPI release :)

**Comment by mihai-tiriplica-hs** [comment]
I can do the version bump later tonight.

**Comment by tiriplicamihai** [comment]
@felixonmars I created a PR for bumping version: https://github.com/snowballstem/pystemmer/pull/29

**Comment by felixonmars** [comment]
I have pushed the release to PyPI. Thanks!

**Pull request merged**
