### PR TITLE
Add Python 3.9 to the test matrix

### PR DESCRIPTION
**Pull request by stefanor**

### CODE REVIEW

**Comment by ojwb** [comment]
Thanks - travis is taking an age, but will merge assuming that eventually passes.

`README.rst` could do with a similar update as it lists versions we've tested with, but I'll take care of that.

**Comment by stefanor** [comment]
Ah, yeah, I'd intended to do that too.

**Comment by stefanor** [comment]
Passed on 3.8 and 3.9, which I guess is what matters.

Should probably migrate to gitlab actions, which is far better resourced for Free Software, these days...

**Comment by ojwb** [comment]
The code change passed for everything: https://travis-ci.org/github/snowballstem/pystemmer/builds/756151933

I manually nuked the CI build for the extra doc-only change as travis seems to be backlogged and others are probably waiting for their builds too.

**Comment by ojwb** [comment]
> Should probably migrate to gitlab actions, which is far better resourced for Free Software, these days...

I guess that would mean moving the code hosting to gitlab too, so that the merge request/gitlab CI integration works?

Not that I'm against doing that, but I think it would be unhelpful to split the snowballstem repos between hosting sites, so that would really require migrating the snowball repo's CI and the website hosting, which are extra tasks I don't really have time for at the moment.  If someone else is keen to make it happen though...

(Or we find someone to take over pystemmer maintainership, which is something I'd like to happen - there's enough work just taking care of the Snowball language, compiler and algorithms.  We don't try to maintain bindings for other languages, and pystemmer is really only here because Richard created it back when he was a Snowball maintainer.)

**Comment by stefanor** [comment]
Sorry, I meant GitHub Actions.

**Comment by ojwb** [comment]
> Sorry, I meant GitHub Actions.

OK - I think that probably would also need someone to contribute a patch.

**Pull request merged**
